// packages/cli/templates/react/src/tools/DemoTool.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@codeexpander/dev-tools-ui";

export default function DemoTool() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Demo Tool</CardTitle>
        <CardDescription>在此添加你的工具逻辑</CardDescription>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-muted-foreground">编辑 src/tools/DemoTool.tsx 开始开发</p>
      </CardContent>
    </Card>
  );
}

// dev-tools/cli/templates/vue/src/tools/DemoTool.vue
<script setup lang="ts">
// 在此添加你的工具逻辑
</script>

<template>
  <div class="rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 p-4 shadow-sm">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100">Demo Tool</h3>
    <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">在此添加你的工具逻辑</p>
    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">编辑 src/tools/DemoTool.vue 开始开发</p>
  </div>
</template>
